"""initial_schema

Revision ID: fbe1e6838981
Revises: 
Create Date: 2026-04-10 15:23:16.676795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fbe1e6838981'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_resource', sa.String(length=255), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_logs_admin_id'), 'admin_audit_logs', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_created_at'), 'admin_audit_logs', ['created_at'], unique=False)
    op.create_table('daily_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_bookings', sa.Integer(), nullable=False),
    sa.Column('completed_bookings', sa.Integer(), nullable=False),
    sa.Column('cancelled_bookings', sa.Integer(), nullable=False),
    sa.Column('failed_bookings', sa.Integer(), nullable=False),
    sa.Column('active_workers', sa.Integer(), nullable=False),
    sa.Column('online_workers', sa.Integer(), nullable=False),
    sa.Column('busy_workers', sa.Integer(), nullable=False),
    sa.Column('average_worker_rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('average_job_duration_minutes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('dispatch_success_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cancellation_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('dispute_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('notifications_sent', sa.Integer(), nullable=False),
    sa.Column('notifications_failed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_metrics_date'), 'daily_metrics', ['date'], unique=True)
    op.create_table('dispatch_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DISPATCHING', 'ASSIGNED', 'FAILED', name='dispatchstatus'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('assigned_worker_id', sa.UUID(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_queue_booking_id'), 'dispatch_queue', ['booking_id'], unique=True)
    op.create_table('disputes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('reported_by', sa.UUID(), nullable=False),
    sa.Column('reported_role', sa.String(length=20), nullable=False),
    sa.Column('dispute_type', sa.Enum('NO_SHOW', 'POOR_SERVICE', 'DAMAGE', 'PAYMENT_ISSUE', 'SAFETY_CONCERN', 'OTHER', name='disputetype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_INVESTIGATION', 'AWAITING_RESPONSE', 'RESOLVED', 'ESCALATED', 'CLOSED', name='disputestatus'), nullable=False),
    sa.Column('assigned_admin_id', sa.UUID(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disputes_booking_id'), 'disputes', ['booking_id'], unique=True)
    op.create_table('error_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('request_path', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_logs_created_at'), 'error_logs', ['created_at'], unique=False)
    op.create_table('notification_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('PUSH', 'SMS', 'EMAIL', 'IN_APP', name='notificationchannel'), nullable=False),
    sa.Column('template_title', sa.String(length=255), nullable=False),
    sa.Column('template_body', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('recipient_type', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.Enum('PUSH', 'SMS', 'EMAIL', 'IN_APP', name='notificationchannel'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'RETRYING', name='notificationstatus'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_table('performance_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('response_time_ms', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_metrics_created_at'), 'performance_metrics', ['created_at'], unique=False)
    op.create_table('report_exports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_type', sa.Enum('API', 'DISPATCH', 'NOTIFICATION', 'DATABASE', 'WORKER', 'SCHEDULER', name='servicetype'), nullable=False),
    sa.Column('event_type', sa.Enum('ERROR', 'WARNING', 'INFO', 'CRITICAL', name='systemeventtype'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_events_created_at'), 'system_events', ['created_at'], unique=False)
    op.create_table('worker_availability',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('OFFLINE', 'ONLINE', 'BUSY', 'ON_BREAK', name='availabilitystatus'), nullable=False),
    sa.Column('current_latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('current_longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_availability_worker_id'), 'worker_availability', ['worker_id'], unique=True)
    op.create_table('worker_performance_metrics',
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('total_jobs_completed', sa.Integer(), nullable=False),
    sa.Column('total_jobs_failed', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('average_job_duration_minutes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('worker_id')
    )
    op.create_table('dispute_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dispute_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dispute_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dispute_id', sa.UUID(), nullable=False),
    sa.Column('previous_status', sa.Enum('OPEN', 'UNDER_INVESTIGATION', 'AWAITING_RESPONSE', 'RESOLVED', 'ESCALATED', 'CLOSED', name='disputestatus'), nullable=False),
    sa.Column('new_status', sa.Enum('OPEN', 'UNDER_INVESTIGATION', 'AWAITING_RESPONSE', 'RESOLVED', 'ESCALATED', 'CLOSED', name='disputestatus'), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dispute_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dispute_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('sender_role', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dispute_messages')
    op.drop_table('dispute_messages')
    op.drop_table('dispute_logs')
    op.drop_table('dispute_evidence')
    op.drop_table('worker_performance_metrics')
    op.drop_index(op.f('ix_worker_availability_worker_id'), table_name='worker_availability')
    op.drop_table('worker_availability')
    op.drop_index(op.f('ix_system_events_created_at'), table_name='system_events')
    op.drop_table('system_events')
    op.drop_table('report_exports')
    op.drop_index(op.f('ix_performance_metrics_created_at'), table_name='performance_metrics')
    op.drop_table('performance_metrics')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('notification_templates')
    op.drop_index(op.f('ix_error_logs_created_at'), table_name='error_logs')
    op.drop_table('error_logs')
    op.drop_index(op.f('ix_disputes_booking_id'), table_name='disputes')
    op.drop_table('disputes')
    op.drop_index(op.f('ix_dispatch_queue_booking_id'), table_name='dispatch_queue')
    op.drop_table('dispatch_queue')
    op.drop_index(op.f('ix_daily_metrics_date'), table_name='daily_metrics')
    op.drop_table('daily_metrics')
    op.drop_index(op.f('ix_admin_audit_logs_created_at'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_admin_id'), table_name='admin_audit_logs')
    op.drop_table('admin_audit_logs')
    # ### end Alembic commands ###
